# Generated by Django 4.2.7 on 2024-02-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_journalbookmarkmodel_journalcommentmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalcommentmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='journalcommentmodel',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='journaldownloadsmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='journaldownloadsmodel',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='journalratingmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='journalratingmodel',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='journalviewsmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='journalviewsmodel',
            name='journal',
        ),
        migrations.AddField(
            model_name='journalmodel',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='deadline'),
        ),
        migrations.DeleteModel(
            name='JournalBookmarkModel',
        ),
        migrations.DeleteModel(
            name='JournalCommentModel',
        ),
        migrations.DeleteModel(
            name='JournalDownloadsModel',
        ),
        migrations.DeleteModel(
            name='JournalRatingModel',
        ),
        migrations.DeleteModel(
            name='JournalViewsModel',
        ),
    ]
