# Generated by Django 4.2.7 on 2024-02-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_rename_author_journalmodel_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalmodel',
            name='deadline',
            field=models.DateTimeField(null=True, verbose_name='deadline'),
        ),
    ]
