# Generated by Django 4.2.7 on 2024-02-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.AddField(
            model_name='customuser',
            name='facebook',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='instagram'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='telegram'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='video',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='video'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='website'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='whatsapp'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='youtube',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='youtube'),
        ),
    ]
