# Generated by Django 4.2.7 on 2024-02-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_address_alter_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='website',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='youtube',
        ),
    ]
