# Generated by Django 5.0.2 on 2024-03-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinamic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='title',
            field=models.CharField(blank='', max_length=50, null='', verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='title_en',
            field=models.CharField(blank='', max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='title_ru',
            field=models.CharField(blank='', max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='title_uz',
            field=models.CharField(blank='', max_length=50, null=True, verbose_name='title'),
        ),
    ]
