# Generated by Django 5.0.2 on 2024-03-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinamic', '0002_alter_aboutmodel_title_alter_aboutmodel_title_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='title_uz',
        ),
    ]
