# Generated by Django 5.0.2 on 2024-03-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinamic', '0003_remove_aboutmodel_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='detail',
            field=models.TextField(blank='', null='', verbose_name='detail'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='detail_en',
            field=models.TextField(blank='', null=True, verbose_name='detail'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='detail_ru',
            field=models.TextField(blank='', null=True, verbose_name='detail'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='detail_uz',
            field=models.TextField(blank='', null=True, verbose_name='detail'),
        ),
    ]
