# Generated by Django 5.0.2 on 2024-03-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinamic', '0004_alter_aboutmodel_detail_alter_aboutmodel_detail_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='url'),
        ),
    ]
