# Generated by Django 5.0.2 on 2024-03-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinamic', '0005_aboutmodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='description',
            field=models.CharField(default='definitely change that!', max_length=150, verbose_name='description'),
        ),
    ]
